### ISSUE TITLE
Make skeleton customizable

### ISSUE THREAD

**Issue by patcon** [Numergy/knife-skeleton#5]
Would be awesome if this was extensible? Also, any thoughts on how this compares with `berks cookbook` command?

**Comment by PierreRambaud** [comment]
Hi,

Can you tell me more about what do you think? Is it about, the capability to skip some files and options(such as foodcritic, rubocop, ...)?

Regards

**Comment by patcon** [comment]
Hm. Think more that I'd like to use your command, but use config to point it to my own directory instead of your "templates" directory:
https://github.com/Numergy/knife-skeleton/tree/master/templates

Perhaps you could [pull it in as a submodule](https://github.com/Numergy/knife-skeleton/tree/master/templates), and people could fork that repo and customize it, and then add something to `knife.rb` to use that instead? :)

**Comment by patcon** [comment]
Ah, hey, looking more closely, this would require that "files" and "templates" go into the same directory, but that would seem entirely possible, since the "erb" suffix could be used to distinguish, right?

**Comment by PierreRambaud** [comment]
It could be better to only add `knife[:skeleton_template_directory]` that overriding path. And by the way moving all `files` into `templates`.

**Comment by patcon** [comment]
Agreed. I'll need this soon, so I'll submit a PR :) 

Also, this is another Pr, but would also like to add something for chef-repo skeletons. I'll open another ticket to discuss

**Comment by PierreRambaud** [comment]
You can try with this branch, and tell me if it's what you want ;)

**Comment by patcon** [comment]
Awesome! Thanks man! Will do

**Comment by PierreRambaud** [comment]
I just create a PR: https://github.com/Numergy/knife-skeleton/pull/9
You can have a look and add :+1:  if you're agree ;)

**Comment by PierreRambaud** [comment]
Gentle ping!

**Comment by PierreRambaud** [comment]
No response for three months, I can close this issue.
