### ISSUE TITLE
`knife skeleton --help` provides no output

### ISSUE THREAD

**Issue by patcon** [Numergy/knife-skeleton#6]
Seems like this just replaces `knife cookbook create`, so it shows up with `knife cookbook --help` and `knife cookbook create --help`. Would you be alright with my submitting a PR to make this command a bit less intrusive. I've just never seen a knife command work like this :)

**Comment by patcon** [comment]
haha also, just realized there's a typo for "COOKOOK"  :D

**Comment by PierreRambaud** [comment]
Hi,
Yes, Knife-skeleton only override the `knife cookbook create` and does not have any `skeleton` subcommand.
Don't hesitate to make a PR, I will be glad to review it :)

Regards
