### ISSUE TITLE
Thoughts

### ISSUE THREAD

**Issue by patcon** [Numergy/knife-skeleton#7]
Finding lots of competing alternatives via this thread:
https://github.com/berkshelf/berkshelf/pull/438

I don't suppose you were aware of them? Going to take some time to evaluate options, and can keep you posted if you're interested. Please ignore my other open issues for now

**Comment by PierreRambaud** [comment]
Hi,
Don't know this option was available, I only use berkshelf for cookbook dependencies.
But if you're interessting about this feature, don't hesitate to test the `custom-template` branch and if your ok, as you said, I can do the same for `chef-repo` quickly.
For example a `knife repo create` command.

Regards

**Comment by patcon** [comment]
Hey Pierre, I did test it out and am very appreciative, but when filing some bugs, I realized there were already some things out there. It might even be possible to alias `chef generate cookbook` to `knife skeleton create COOKBOOK --generator-cookbook /path/to/generator`

Anyhow, I'll be investigating. Not sure I like the idea of a "generator cookbook", as a directory of erb's might be simpler to grok and fork

**Comment by PierreRambaud** [comment]
With the patch on the branch you can use `knife cookbook create COOKBOOK_NAME --template_directory /path/to/directory` containing a list of *.erb files.

It's possible and easy to come back to a skeleton command, for examples:
`knife skeleton cookbook create`
`knife skeleton repo create`
And both will have approximately the sames parameters.

**Comment by PierreRambaud** [comment]
No response for three months, I can close this issue.
